apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-web-site
  name: my-web-site
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-site
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-web-site
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80