{{- if and .Values.ingress.enabled (eq .Values.ingress.type "alb") -}}
apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
metadata:
  name: {{ .Values.ingress.paramsName }}
spec:
  group:
    name: {{ .Values.ingress.groupName }}
  scheme: {{ .Values.ingress.scheme }}
{{- end }}