{{- if and .Values.ingress.enabled (eq .Values.ingress.type "alb") -}}
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: {{ .Values.ingress.className}}
spec:
  controller: ingress.k8s.aws/alb
  parameters:
    apiGroup: elbv2.k8s.aws
    kind: IngressClassParams
    name: {{ .Values.ingress.paramsName }}
{{- end }}